(ns repl.repl.team-names)

(def nums (range 1367 9637))

(def en+es
  [:alligator-caimán
   :almonds-almendras
   :apple-manzana
   :art-arte
   :aunt-tía
   :autumn-otoño
   :baby-bebé
   :bad-malo
   :banana-plátano
   :bank-banco
   :beach-playa
   :beans-frijoles
   :bear-oso
   :bed-cama
   :bedroom-dormitorio
   :big-grande
   :bird-pájaro
   :birds-las-aves
   :bitter-amargo
   :black-negro
   :blue-azul
   :book-libro
   :bread-pan
   :breakfast-desayuno
   :brother-hermano
   :brown-marrón
   :bull-toro
   :butter-mantequilla
   :cafe-café
   :candy-dulce
   :carrot-zanahoria
   :cat-gato
   :ceiling-techo
   :chair-silla
   :cheese-queso
   :chicken-pollo
   :clean-limpio
   :clothes-ropa
   :cloudy-nublado
   :coat-abrigo
   :cold-frío
   :colors-colores
   :cool-fresco
   :corn-maíz
   :correct-correcto
   :country-país
   :cousin-primo
   :cow-vaca
   :cucumber-pepino
   :cumin-comino
   :cup-taza
   :dark-oscuro
   :daughter-hija
   :days-días
   :deep-profundo
   :deer-venado
   :dentist-dentista
   :desert-desierto
   :desk-escritorio
   :dessert-postre
   :difficult-difícil
   :dinner-cena
   :dirty-sucio
   :doctor-médico
   :dog-perro
   :donkey-burro
   :dress-vestido
   :dry-seco
   :eagle-águila
   :earth-tierra
   :easy-fácil
   :elephant-elefante
   :empty-vacío
   :expensive-caro
   :fast-rápido
   :father-padre
   :fish-pescado
   :floor-piso
   :flowers-flores
   :foggy-brumoso
   :food-comida
   :football-fútbol
   :foreign-extranjero
   :forest-bosque
   :fork-tenedor
   :fresh-fresco
   :friday-viernes
   :fruit-frutas
   :full-completo
   :furniture-muebles
   :game-juego
   :garden-jardín
   :garlic-ajo
   :geography-geografía
   :giraffe-jirafa
   :glass-vidrio
   :goat-cabra
   :good-bueno
   :grandfather-abuelo
   :grandmother-abuela
   :grapes-uvas
   :gray-gris
   :green-verde
   :hard-duro
   :hat-sombrero
   :heavy-pesado
   :history-historia
   :horse-caballo
   :hot-caliente
   :hour-hora
   :house-casa
   :how-cómo
   :husband-marido
   :ice-cream-helado
   :ice-hielo
   :inexpensive-barato
   :ink-tinta
   :island-isla
   :jacket-chaqueta
   :kitchen-cocina
   :knife-cuchillo
   :lake-lago
   :lamb-cordero
   :lamp-lámpara
   :lemon-limón
   :letter-carta
   :lettuce-lechuga
   :library-biblioteca
   :light-ligero
   :lion-león
   :local-local
   :long-largo
   :lunch-almuerzo
   :map-mapa
   :math-matemáticas
   :meal-comida
   :meat-carne
   :mice-ratones
   :minute-minuto
   :monday-lunes
   :monkey-mono
   :moon-luna
   :mother-madre
   :mountain-montaña
   :mouse-ratón
   :movies-cine
   :music-música
   :narrow-estrecho
   :nephew-sobrino
   :new-nuevo
   :newspaper-periódico
   :niece-sobrina
   :noisy-ruidoso
   :notebook-cuaderno
   :nurse-enfermera
   :objects-objetos
   :ocean-océano
   :office-oficina
   :old-viejo
   :olives-aceitunas
   :on-foot-a-pie
   :onions-cebollas
   :orange-naranja
   :oranges-naranjas
   :oven-horno
   :pants-pantalones
   :paper-papel
   :peaches-duraznos
   :peanut-maní
   :pears-peras
   :pen-pluma
   :pencil-lápiz
   :people-personas
   :pepper-pimienta
   :pharmacy-farmacia
   :picture-foto
   :pineapple-piña
   :plants-plantas
   :plate-placa
   :player-jugador
   :policeman-policía
   :pork-carne-de-cerdo
   :postman-cartero
   :potatoes-patatas
   :pouring-verter
   :powerful-poderoso
   :professor-profesor
   :pumpkin-calabaza
   :purple-púrpura
   :qualities-cualidades
   :questions-preguntas
   :quiet-tranquilo
   :rabbit-conejo
   :rain-lluvia
   :raining-lloviendo
   :red-rojo
   :river-río
   :roof-techo
   :room-habitación
   :rug-alfombra
   :salad-ensalada
   :salt-sal
   :salty-salado
   :sandwich-sándwich
   :saturday-sábado
   :sausage-salchicha
   :science-ciencia
   :scissors-tijeras
   :sea-mar
   :second-segundo
   :shampoo-champú
   :shirt-camisa
   :shoes-zapatos
   :short-corto
   :sizes-tamaños
   :sky-cielo
   :slow-lento
   :small-pequeño
   :snake-serpiente
   :snakes-serpientes
   :snow-nieve
   :snowing-nevando
   :soap-jabón
   :soccer-fútbol
   :socks-calcetines
   :soft-suave
   :son-hijo
   :soup-sopa
   :sour-agrio
   :spicy-picante
   :spoon-cuchara
   :spring-primavera
   :stars-estrellas
   :strawberries-fresas
   :sugar-azúcar
   :summer-verano
   :sunday-domingo
   :sunny-soleado
   :supper-cena
   :sweet-dulce
   :table-tabla
   :tall-alto
   :teacher-profesor
   :telephone-teléfono
   :that-que
   :theater-teatro
   :these-estos
   :thick-espeso
   :thin-delgado
   :those-aquellos
   :thursday-jueves
   :tiger-tigre
   :time-tiempo
   :tomatoes-tomates
   :towel-toalla
   :tree-árbol
   :tuesday-martes
   :turkey-pavo
   :umbrella-paraguas
   :uncle-tío
   :very-muy
   :wall-pared
   :wallet-cartera
   :weak-débil
   :weather-tiempo
   :wednesday-miércoles
   :wet-mojado
   :what-qué
   :where-dónde
   :white-blanco
   :who-quién
   :why-por-qué
   :wide-ancho
   :wife-esposa
   :window-ventana
   :windy-ventoso
   :winter-invierno
   :wolf-lobo
   :wrong-mal
   :yellow-amarillo
   :young-joven])

(defn gen-name
  []
  (let [names   (map name (take 2 (shuffle en+es)))
        numbers (take 2 (shuffle nums))]
    (->> (interleave names numbers)
         (interpose "-")
         (apply str))))